# Generated by Django 5.2.4 on 2025-08-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_remove_profile_category_remove_profile_dp_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_role",
            field=models.CharField(
                choices=[("buyer", "Buyer"), ("seller", "Seller")],
                default="buyer",
                max_length=20,
            ),
        ),
    ]
