# Generated by Django 5.2.4 on 2025-08-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0004_alter_profile_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="address",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone_number",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="profile",
            name="user_role",
            field=models.CharField(choices=[("buyer", "Buyer"), ("seller", "Seller")]),
        ),
    ]
