# Generated by Django 5.1.1 on 2025-08-25 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_alter_profile_address_alter_profile_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="user_role",
            field=models.CharField(
                choices=[("buyer", "Buyer"), ("seller", "Seller")], max_length=6
            ),
        ),
    ]
