# Generated by Django 5.2.4 on 2025-10-26 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_order_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Category",
            new_name="category",
        ),
    ]
